_________________________________________________________________________

## PRACTICA OBLIGATORIA: ALGEBRA Y NUMPY

* La práctica obligatoria de esta unidad consiste en dos ejercicios de programación libre a completar. Descarga este notebook en tu ordenador y trabaja en local.  
* Recuerda que debes subirla a tu repositorio personal antes de la sesión en vivo para que puntúe adecuadamente.  
* Recuerda también que no es necesario que esté perfecta, sólo es necesario que se vea el esfuerzo. 
* Esta práctica se resolverá en la sesión en vivo correspondiente y la solución se publicará en el repo del curso. 


## PARTE I: ¿Dónde me pongo como el Kiko?

Rafa, Nacho y Clara quieren comprar palmeras, donuts, hojaldres y tartas. Cada uno necesita diferentes cantidades y pueden elegir dos tiendas: *Manolo Bakes* y *Starbucks*. 

Las siguiente tablas muestran, respectivamente, la cantidad que cada uno necesita, y los precios en cada una de las tiendas

<table><thead><tr><th></th><th>Palmeras</th><th>Donuts</th><th>Hojaldres</th><th>Tartas</th></tr></thead><tbody><tr><td>Rafa</td><td>6</td><td>5</td><td>3</td><td>1</td></tr><tr><td>Nacho</td><td>3</td><td>6</td><td>2</td><td>2</td></tr><tr><td>Clara</td><td>3</td><td>4</td><td>3</td><td>1</td></tr></tbody></table>

<table><thead><tr><th></th><th>Manolo Bakes</th><th>Starbucks</th></tr></thead><tbody><tr><td>Palmera</td><td>1.50</td><td>1.00</td></tr><tr><td>Donut</td><td>2.00</td><td>2.50</td></tr><tr><td>Hojaldre</td><td>5.00</td><td>4.50</td></tr><tr><td>Tarta</td><td>16.00</td><td>17.00</td></tr></tbody></table>

Por ejemplo, si Rafa compra en *Manolo Bakes* gastaría:  

$6\cdot1.50+5\cdot2+3\cdot5+1\cdot16=50$  

y si compra en *Starbucks* gastaría:  

$6\cdot1+5\cdot2.50+3\cdot4.50+1\cdot17=49$  

**SE PIDE**: Genera la matriz que exprese la cantidad que cada persona gastaría en cada tienda, y recomienda a cada uno dónde debería hacer sus compras (pista: donde le cueste menos, ¿no?)

**REQUISITIO**: Emplea Numpy, su tipo array y sus operaciones para la resolución del ejercicio. 

In [20]:
import numpy as np

personas_pedido = np.array([
    [6, 5, 3, 1],   
    [3, 6, 2, 2],   
    [3, 4, 3, 1]    
])
precios = np.array([
    [1.50, 1.00],  
    [2.00, 2.50],  
    [5.00, 4.50],  
    [16.00, 17.00] 
])
gastos_manolo = np.dot(personas_pedido, precios[:, 0])  
gastos_starbucks = np.dot(personas_pedido, precios[:, 1]) 

matriz_gastos = np.array([gastos_manolo, gastos_starbucks]).T

personas = ['Rafa', 'Nacho', 'Clara']
tiendas = ['Manolo Bakes', 'Starbucks']

print("Matriz de gastos (cada fila es [Manolo Bakes, Starbucks]):")
for i, persona in enumerate(personas):
    print(f"{persona}: {matriz_gastos[i]}")

for i, persona in enumerate(personas):
    if gastos_manolo[i] < gastos_starbucks[i]:
        mejor_tienda = "Manolo Bakes"
    else:
        mejor_tienda = "Starbucks"
    print(f"{persona} debería comprar en {mejor_tienda}.")


Matriz de gastos (cada fila es [Manolo Bakes, Starbucks]):
Rafa: [50. 49.]
Nacho: [58.5 61. ]
Clara: [43.5 43.5]
Rafa debería comprar en Starbucks.
Nacho debería comprar en Manolo Bakes.
Clara debería comprar en Starbucks.


**BONUS (Voluntario):**  
Expresa utilizando markdown y laTex las matrices y las operaciones que has realizado. Recuerda que para invocar LaTex denro de markdown se emplea $, y $$ si queremos que esté centrado. Y que [aquí](https://ashki23.github.io/markdown-latex.html#latex "Latex y Markdown") tienes muchos ejemplos de como trabajar con latex

_________________________________________________________________________

## PARTE II: Clasificador de Películas

II.1: Similitud entre películas

Vamos a calcular similitudes entre películas. Para ello las clasificasmos según generos, en concreto tenemos:

* Toy Story: Aventura, Animación, Comedia
* Jumanji: Aventura   
* Mortal Kombat: Acción, Aventura  
* Pocahontas: Animación, Romance

Y ahora calcularemos su similitud por el método del coseno. Para ello:

1. Convierte cada película en un vector y almacenalo en un diccionario con clave el nombre de la película. Pista: Para convertirlo en vector, crea un vector/lista por película con esta estructura (¿qué valores puedes darle por género?):

$$[Acción,  Aventura , Animación, Comedia, Romance]$$

In [22]:
import numpy as np


peliculas = {
    "Toy Story": ["Aventura", "Animación", "Comedia"],
    "Jumanji": ["Aventura"],
    "Mortal Kombat": ["Acción", "Aventura"],
    "Pocahontas": ["Animación", "Romance"]
}
generos_unicos = list(set(genero for generos in peliculas.values() 
                          for genero in generos))

vectores_peliculas = {pelicula: [1 if genero in generos 
                                 else 0 
                                 for genero in generos_unicos]
                      for pelicula, generos in peliculas.items()}

2. Crea una matriz de películas con un array de numpy. Muestra la dimension, shape, tamaño y tipo del array.


In [21]:
matriz_peliculas = np.array(list(vectores_peliculas.values()))
print("Matriz de películas:")
print(matriz_peliculas)
print("Dimensiones:", matriz_peliculas.ndim)
print("Shape:", matriz_peliculas.shape)
print("Tamaño:", matriz_peliculas.size)
print("Tipo:", matriz_peliculas.dtype)

Matriz de películas:
[[1 0 1 1 0]
 [1 0 0 0 0]
 [1 0 0 0 1]
 [0 1 1 0 0]]
Dimensiones: 2
Shape: (4, 5)
Tamaño: 20
Tipo: int64


3. A partir de la similitud por coseno (recuerda a mayor coseno entre vectore más similitud), genera un programa que calcule la similitud entre cada pelicula y nos diga cuales son las más parecidas entre sí.

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
def similitud_coseno(A, B):
    producto_punto = np.dot(A, B)
    norma_A = np.linalg.norm(A)
    norma_B = np.linalg.norm(B)
    if norma_A == 0 or norma_B == 0: 
        return 0
    return producto_punto / (norma_A * norma_B)

peliculas_similares = []
num_peliculas = len(peliculas)

for i in range(num_peliculas):
    for j in range(i + 1, num_peliculas):
        pelicula1 = list(peliculas.keys())[i]
        pelicula2 = list(peliculas.keys())[j]
        similitud = similitud_coseno(matriz_peliculas[i], matriz_peliculas[j])
        peliculas_similares.append((pelicula1, pelicula2, similitud))

print("Similitudes entre películas:")
for pelicula1, pelicula2, similitud in peliculas_similares:
    print(f"Similitud entre {pelicula1} y {pelicula2}: {similitud:.4f}")



Similitudes entre películas:
Similitud entre Toy Story y Jumanji: 0.5774
Similitud entre Toy Story y Mortal Kombat: 0.4082
Similitud entre Toy Story y Pocahontas: 0.4082
Similitud entre Jumanji y Mortal Kombat: 0.7071
Similitud entre Jumanji y Pocahontas: 0.0000
Similitud entre Mortal Kombat y Pocahontas: 0.0000


**BONUS (Voluntario)**:

A Jaimolas le encanta la premoritoria pelicula Wall-E (Aventura, Comedia, Acción), ¿qué película de las anteriores le recomendaríamos?